<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AddSecretFilter</name>
   <tag></tag>
   <elementGuidId>38110011-7a0b-4384-92bc-12c0a1810482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium.grid.security&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AddSecretFilter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f36b13c5-86f2-47d6-9009-857bc2b021b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/grid/security/AddSecretFilter.html</value>
      <webElementGuid>f44b99cf-bbb5-4b0b-9fe9-b8066312be94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.grid.security</value>
      <webElementGuid>04e653f0-a269-437b-8847-d8ef382e6b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>c760b60c-4c9e-4020-8506-e8bcf5d77a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AddSecretFilter</value>
      <webElementGuid>c290a393-bfaf-475b-b459-908f35a67926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[31]/a[1]</value>
      <webElementGuid>823274c9-6b78-4b90-b182-75dd640d51c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_AddHasCdp/iframe_packageFrame</value>
      <webElementGuid>9a7f95cd-5659-42d0-83b9-15faf7617a0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AddSecretFilter')]</value>
      <webElementGuid>39ac9938-1bc1-49f6-82f2-5554325a8176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AdditionalHttpCommands'])[1]/following::a[1]</value>
      <webElementGuid>1a06fe3b-82fa-4d98-b2de-f86f72bb7dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasPermissions'])[2]/following::a[2]</value>
      <webElementGuid>baa62798-b646-4ad5-8279-1aace16f8d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddSeleniumUserAgent'])[1]/preceding::a[1]</value>
      <webElementGuid>6fe42b4a-dbce-49b7-9039-f3724f23b030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddWebDriverSpecHeaders'])[1]/preceding::a[2]</value>
      <webElementGuid>cf7554ba-0f6b-4c8a-a299-344d279d2a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AddSecretFilter']/parent::*</value>
      <webElementGuid>f9877726-a983-4bba-8d89-d11070d6bf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/grid/security/AddSecretFilter.html')]</value>
      <webElementGuid>954e0d04-311f-4c8f-954a-593e5cf7beea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[31]/a</value>
      <webElementGuid>723e88c1-1bd8-4a0f-b232-87a536540035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/grid/security/AddSecretFilter.html' and @title = 'class in org.openqa.selenium.grid.security' and (text() = 'AddSecretFilter' or . = 'AddSecretFilter')]</value>
      <webElementGuid>aff259f4-927f-47e0-92ff-bc5fc471db0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
