<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AbstractHttpResponseCodec</name>
   <tag></tag>
   <elementGuidId>2ed5e5e8-f990-49b4-bb0e-770fb7a893d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AbstractHttpResponseCodec')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>420f4a25-0311-4858-812e-894c244067d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html</value>
      <webElementGuid>00283fb5-307f-46d0-a031-d3256c7171cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.remote.codec</value>
      <webElementGuid>1726cb9f-2660-41ff-8985-8fb14a8ca83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>99215bbd-4b25-44b7-9c0a-8ebe1b58ba22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AbstractHttpResponseCodec</value>
      <webElementGuid>11db62fe-7ff4-4288-bd2f-3a60bc882f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[6]/a[1]</value>
      <webElementGuid>611eb396-5340-4a01-a9cf-dc1f7b391109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_AbstractDriverOptions/iframe_packageFrame</value>
      <webElementGuid>0893ae88-7c67-4c28-989c-510cc07f03de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AbstractHttpResponseCodec')]</value>
      <webElementGuid>d754a77d-84f8-4dea-81c8-3035a0311a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec.CommandSpec'])[1]/following::a[1]</value>
      <webElementGuid>2cd8c0db-27fb-4425-ab53-e245c50355e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractHttpCommandCodec'])[1]/following::a[2]</value>
      <webElementGuid>0da5bbe6-7000-4771-96b0-817b0023902b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbstractWebDriverEventListener'])[1]/preceding::a[1]</value>
      <webElementGuid>0b22ce5e-8ea1-4d0d-b0c6-60c9ebd3ba55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AcceptedW3CCapabilityKeys'])[1]/preceding::a[2]</value>
      <webElementGuid>168ee7a6-e72c-47e9-a17c-c82d453f65ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AbstractHttpResponseCodec']/parent::*</value>
      <webElementGuid>2410eb6b-13bb-4dcc-8df1-6ad756c524c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html')]</value>
      <webElementGuid>a72c25a1-4aed-4108-a157-25e4b947a468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>475b1670-7be3-4401-ace6-37fcce3bf92d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/remote/codec/AbstractHttpResponseCodec.html' and @title = 'class in org.openqa.selenium.remote.codec' and (text() = 'AbstractHttpResponseCodec' or . = 'AbstractHttpResponseCodec')]</value>
      <webElementGuid>1402bf15-60d1-47e4-8495-d3ba5099f1b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
