<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AddHasCdp</name>
   <tag></tag>
   <elementGuidId>7a7a5578-2087-4728-8743-e5c010325248</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AddHasCdp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54a84beb-4a1c-408e-989a-e77d230d2db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/chrome/AddHasCdp.html</value>
      <webElementGuid>2a5b2325-3495-413d-b660-8b528a82a8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.chrome</value>
      <webElementGuid>0c2b4c26-6a67-4b90-9d4b-a08c4bbe48cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>e0d88b00-f66a-4cda-8395-075c7fdc3b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AddHasCdp</value>
      <webElementGuid>0c94f39a-19e8-4dee-bd69-aa2c17c6afa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[18]/a[1]</value>
      <webElementGuid>7b236f66-c4d3-48b9-a61c-d83727cb4cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_AbstractHttpResponseCodec/iframe_packageFrame</value>
      <webElementGuid>c88151b8-281f-4054-b29b-56d520c78608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AddHasCdp')]</value>
      <webElementGuid>ce488633-77f4-464e-86cb-acdf9fcb082b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasCasting'])[3]/following::a[1]</value>
      <webElementGuid>524580de-2ed5-4b7d-b722-8190df13c848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasCasting'])[2]/following::a[2]</value>
      <webElementGuid>564289c4-f930-4405-9943-6f9f23d9653f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasCdp'])[2]/preceding::a[1]</value>
      <webElementGuid>d351c684-8e00-45d7-b38b-4d43b6f3826a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddHasCdp'])[3]/preceding::a[2]</value>
      <webElementGuid>64c7b403-a0a8-4406-ab01-04fdbfe2fc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AddHasCdp']/parent::*</value>
      <webElementGuid>eb77bea9-cb20-4cbf-9bc7-f7fbab88ed84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/chrome/AddHasCdp.html')]</value>
      <webElementGuid>4ab91ab9-98e0-4314-a385-66a77a25bd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[18]/a</value>
      <webElementGuid>fe5a9c1f-6a1c-4987-ad8e-4ce3bd39aa50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/chrome/AddHasCdp.html' and @title = 'class in org.openqa.selenium.chrome' and (text() = 'AddHasCdp' or . = 'AddHasCdp')]</value>
      <webElementGuid>dff73271-15c6-442c-bc35-4a4f34744292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
