<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AddWebStorage</name>
   <tag></tag>
   <elementGuidId>9144316c-9223-4e93-adf4-708525c946e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;class in org.openqa.selenium.remote.html5&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AddWebStorage')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bef39267-4329-45db-b266-43a6bb4cc924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/remote/html5/AddWebStorage.html</value>
      <webElementGuid>b1625280-b7ca-44fc-bfcd-86a1eb91eb80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.remote.html5</value>
      <webElementGuid>125dabdd-f213-46b3-a507-06f722d82c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>6e9ffb88-aae0-45a5-b2d5-ffe455d79438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AddWebStorage</value>
      <webElementGuid>94649a1d-5eec-490b-8159-0feeb90eb3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[@class=&quot;indexContainer&quot;]/ul[1]/li[34]/a[1]</value>
      <webElementGuid>9ef656ba-3c5c-48df-8008-4ffa8bc06fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_AddSecretFilter/iframe_packageFrame</value>
      <webElementGuid>c0912435-1783-4cfa-bd59-14232369901c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AddWebStorage')]</value>
      <webElementGuid>6147e6f9-f790-4333-900c-ceae93b715df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddWebDriverSpecHeaders'])[1]/following::a[1]</value>
      <webElementGuid>c3aa044a-17e5-4fe7-b04f-40163f729e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AddSeleniumUserAgent'])[1]/following::a[2]</value>
      <webElementGuid>e909f5f8-83b0-4885-bb75-a40ce05768de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AjaxElementLocator'])[1]/preceding::a[1]</value>
      <webElementGuid>1a547b01-0472-4c20-90d1-8d4546bac55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AjaxElementLocatorFactory'])[1]/preceding::a[2]</value>
      <webElementGuid>7dc1d41c-a801-4b82-a43b-055ec455291d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AddWebStorage']/parent::*</value>
      <webElementGuid>64b93db6-8abf-4067-b765-6e6a8c139b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/remote/html5/AddWebStorage.html')]</value>
      <webElementGuid>1324759e-0dca-44d3-a34d-4c75d4ba5140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[34]/a</value>
      <webElementGuid>2a58054c-1b75-4db6-b2d8-bfef6b48b0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/remote/html5/AddWebStorage.html' and @title = 'class in org.openqa.selenium.remote.html5' and (text() = 'AddWebStorage' or . = 'AddWebStorage')]</value>
      <webElementGuid>711c8ae4-3c36-40f7-9061-ec4e99664ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
